swagger: "2.0"
definitions:
  PetBusinessApplicationRequest:
    type: object
    required:
      - businessEmail
      - businessDescription
      - websiteURL
      - petBusinessId
      - businessType
    properties:
      businessEmail:
        type: string
        description: The business email address that is displayed to the customer.
      businessDescription:
        type: string
        description: The business description of the Pet Business.
      websiteURL:
        type: string
        description: The website URL of the Pet Business.
      petBusinessId:
        type: integer
        description: The unique identifier of the Pet Business associated with this application.
      businessType:
        type: string
        description: The business type of the Pet Business.
      businessAddresses:
        type: array
        items:
          $ref: "#/definitions/BusinessAddress"

  PetBusinessApplicationResponse:
    type: object
    properties:
      petBusinessApplicationId:
        type: integer
        description: The unique identifier of the Pet Business Application.
      businessType:
        type: string
        description: The business type of the Pet Business.
      businessEmail:
        type: string
        description: The business email address that is displayed to the customer.
      businessDescription:
        type: string
        description: The business description of the Pet Business.
      websiteURL:
        type: string
        description: The website URL of the Pet Business.
      attachments:
        type: array
        items:
          type: string
        description: List of attachment URLs/identifiers.
      applicationStatus:
        type: string
        enum: [PENDING, APPROVED, REJECTED]
        description: The status of the application.
      adminRemarks:
        type: array
        items:
          type: string
        description: Remarks given by the admin.
      dateCreated:
        type: string
        format: date-time
        description: The date the application was created.
      lastUpdated:
        type: string
        format: date-time
        description: The last date the application was updated.
      petBusinessId:
        type: integer
        description: The unique identifier of the Pet Business associated with this application.
      approverId:
        type: integer
        description: The ID of the approver.
      businessAddresses:
        type: array
        items:
          $ref: "#/definitions/BusinessAddress"
      approver:
        $ref: "#/definitions/Approver"

  businessAddresses:
    type: array
    description: A list of businesses addresses for this application.
    items:
      type: object
      required:
        - addressName
        - line1
        - postalCode
      properties:
        addressName:
          type: string
          description: The identifier for this address. This is not a unique property.
        line1:
          type: string
          description: Line 1 of the address.
        line2:
          type: string
          description: The optional line 2 of the address.
        postalCode:
          type: string
          description: The postal code of the address.

  Approver:
    type: object
    required:
      - firstName
      - lastName
      - adminRole
      - userId
    properties:
      firstName:
        type: string
        description: First name of the approver.
      lastName:
        type: string
        description: Last name of the approver.
      adminRole:
        type: string
        description: Role of the approver in the system.
      userId:
        type: integer
        description: The unique identifier of the approver.

paths:
  /api/pb-applications/:
    post:
      summary: Register a new pet business application
      description: Create a new pet business application with the specified details.
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: Pet business application details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/PetBusinessApplicationRequest"
            example:
              businessEmail: "pet@petgroom.com"
              businessDescription: "We offer grooming stuff."
              websiteURL: "https://www.petgroom.com"
              petBusinessId: 1
              businessType: "SERVICE"
              businessAddresses:
                - addressName: "Main Office"
                  line1: "123 Paws Street"
                  line2: "Suite 100"
                  postalCode: "12345D"
                - addressName: "Side Office"
                  line1: "321 Paws Street"
                  postalCode: "12345F"

      tags:
        - PetBusinessApplication
      responses:
        201:
          description: Pet business application created successfully
          content:
            application/json:
              schema:
                $ref: "#/definitions/PetBusinessApplicationResponse"
              example:
                petBusinessApplicationId: 13
                businessType: SERVICE
                businessEmail: example@gmail.com
                businessDescription: ello there
                websiteURL: https://www.google.com
                attachments: []
                applicationStatus: PENDING
                adminRemarks:
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 2
                dateCreated: "2023-09-14T08:12:43.130Z"
                lastUpdated: "2023-09-14T08:28:24.971Z"
                petBusinessId: 21
                approverId: null
                businessAddresses:
                  - addressId: 97
                    addressName: address3
                    line1: line1
                    line2: line2
                    postalCode: 12983714
                    petBusinessId: null
                    petBusinessApplicationId: 13
                  - addressId: 98
                    addressName: address4
                    line1: line1
                    line2:
                    postalCode: 12983714
                    petBusinessId: null
                    petBusinessApplicationId: 13

    get:
      summary: Retrieve all pet business applications
      description: Fetch all the pet business applications available in the system. Optionally, filter by status using a query parameter.
      produces:
        - application/json
      parameters:
        - in: query
          name: status
          description: Filter by application status (PENDING, APPROVED, REJECTED).
          schema:
            type: string
            enum: [PENDING, APPROVED, REJECTED]
      tags:
        - PetBusinessApplication
      responses:
        200:
          description: A list of pet business applications.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/PetBusinessApplicationRequest"

  /api/pb-applications/{id}:
    put:
      summary: Update an existing pet business application
      description: Update the details of an existing pet business application.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: Pet Business Application ID.
          schema:
            type: integer
      requestBody:
        description: Pet business application details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/PetBusinessApplicationRequest"
            example:
              businessEmail: "pet@petgroom.com"
              businessDescription: "We offer grooming stuff."
              websiteURL: "https://www.petgroom.com"
              petBusinessId: 1
              businessType: "SERVICE"
              businessAddresses:
                - addressName: "Main Office"
                  line1: "123 Paws Street"
                  line2: "Suite 100"
                  postalCode: "12345D"
                - addressName: "Side Office"
                  line1: "321 Paws Street"
                  postalCode: "12345F"
      tags:
        - PetBusinessApplication
      responses:
        200:
          description: Pet business application updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/definitions/PetBusinessApplicationStatusResponse"
              example:
                petBusinessApplicationId: 13
                businessType: SERVICE
                businessEmail: example@gmail.com
                businessDescription: ello there
                websiteURL: https://www.google.com
                attachments: []
                applicationStatus: PENDING
                adminRemarks:
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 2
                dateCreated: "2023-09-14T08:12:43.130Z"
                lastUpdated: "2023-09-14T08:28:24.971Z"
                petBusinessId: 21
                approverId: null
                businessAddresses:
                  - addressId: 97
                    addressName: address3
                    line1: line1
                    line2: line2
                    postalCode: 12983714
                    petBusinessId: null
                    petBusinessApplicationId: 13
                  - addressId: 98
                    addressName: address4
                    line1: line1
                    line2:
                    postalCode: 12983714
                    petBusinessId: null
                    petBusinessApplicationId: 13

    get:
      summary: Retrieve pet business application by its application ID
      description: Fetch a specific pet business application by its unique application ID.
      parameters:
        - in: path
          name: id
          required: true
          description: Pet Business Application ID.
          schema:
            type: integer
      tags:
        - PetBusinessApplication
      responses:
        200:
          description: Pet business application details.
          content:
            application/json:
              schema:
                $ref: "#/definitions/PetBusinessApplicationRequest"
              example:
                petBusinessApplicationId: 13
                businessType: SERVICE
                businessEmail: example@gmail.com
                businessDescription: ello there
                websiteURL: https://www.google.com
                attachments: []
                applicationStatus: APPROVED
                adminRemarks:
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 2
                dateCreated: "2023-09-14T08:12:43.130Z"
                lastUpdated: "2023-09-14T08:28:24.971Z"
                petBusinessId: 21
                approverId: 1
                businessAddresses:
                  - addressId: 97
                    addressName: address3
                    line1: line1
                    line2: line2
                    postalCode: 12983714
                    petBusinessId: 21
                    petBusinessApplicationId: 13
                  - addressId: 98
                    addressName: address4
                    line1: line1
                    line2:
                    postalCode: 12983714
                    petBusinessId: 21
                    petBusinessApplicationId: 13
                approver:
                  firstName: Jake
                  lastName: TheDog
                  adminRole: ADMINISTRATOR
                  userId: 1
        400:
          description: Invalid ID format provided.
        404:
          description: Pet Business Application not found based on the provided ID.

  /api/pb-applications/pet-business/{id}:
    get:
      summary: Retrieve a specific pet business application by the pet business ID tied to it
      description: Fetch details of a pet business application using the ID of the pet business tied to it.
      parameters:
        - in: path
          name: id
          required: true
          description: Pet Business ID.
          schema:
            type: integer
      tags:
        - PetBusinessApplication
      responses:
        200:
          description: Details of the specified pet business.
          content:
            application/json:
              schema:
                $ref: "#/definitions/PetBusinessApplicationRequest"
              example:
                petBusinessApplicationId: 13
                businessType: SERVICE
                businessEmail: example@gmail.com
                businessDescription: ello there
                websiteURL: https://www.google.com
                attachments: []
                applicationStatus: APPROVED
                adminRemarks:
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 1
                  - Test remark 2
                dateCreated: "2023-09-14T08:12:43.130Z"
                lastUpdated: "2023-09-14T08:28:24.971Z"
                petBusinessId: 21
                approverId: 1
                businessAddresses:
                  - addressId: 97
                    addressName: address3
                    line1: line1
                    line2: line2
                    postalCode: 12983714
                    petBusinessId: 21
                    petBusinessApplicationId: 13
                  - addressId: 98
                    addressName: address4
                    line1: line1
                    line2:
                    postalCode: 12983714
                    petBusinessId: 21
                    petBusinessApplicationId: 13
                approver:
                  firstName: Jake
                  lastName: TheDog
                  adminRole: ADMINISTRATOR
                  userId: 1
        400:
          description: Invalid ID format provided.
        404:
          description: Pet Business not found based on the provided ID.

  /api/pb-applications/status/{id}:
    get:
      summary: Retrieve pet business application status by pet business ID
      description: Fetch the application status of a specific pet business using its unique pet business ID.
      parameters:
        - in: path
          name: id
          required: true
          description: Pet Business ID.
          schema:
            type: integer
      tags:
        - PetBusinessApplication
      responses:
        200:
          description: Pet business application status based on pet business ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                    enum: [PENDING, APPROVED, REJECTED]
        400:
          description: Invalid ID format provided.
        404:
          description: Pet Business Application not found based on the provided ID.

  /api/pb-applications/approve/{id}:
    post:
      summary: Approve a pet business application
      description: Approves a specific pet business application based on its unique ID.
      parameters:
        - in: path
          name: id
          required: true
          description: Pet Business Application ID.
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                approverId:
                  type: integer
                  description: ID of the approver.
      tags:
        - PetBusinessApplication
      responses:
        200:
          description: Pet business application approval details.
          content:
            application/json:
              schema:
                $ref: "#/definitions/PetBusinessApplicationRequest"
        400:
          description: Invalid ID format provided.
        404:
          description: Pet Business Application not found based on the provided ID.

  /api/pb-applications/reject/{id}:
    post:
      summary: Reject a pet business application
      description: Rejects a specific pet business application by its unique ID.
      parameters:
        - in: path
          name: id
          required: true
          description: Pet Business Application ID.
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                remark:
                  type: string
                  description: Remarks for rejection.
      tags:
        - PetBusinessApplication
      responses:
        200:
          description: Pet business application rejection details.
          content:
            application/json:
              schema:
                $ref: "#/definitions/PetBusinessApplicationRequest"
        400:
          description: Invalid ID format provided.
        404:
          description: Pet Business Application not found based on the provided ID.
